### ISSUE TITLE
Change the footer "Published with..."

### ISSUE THREAD

**Issue by etiennebacher** [wowchemy/starter-academic#118] opened 2020-09-10 13:08 UTC
I'm making my blog using this repo (and the `blogdown` R package) and I realized that I can't change the footer "Published with Wowchemy Website Builder". I know that it's possible to add a copyright license (in `config/_default/params.toml`) or a copyright notice (in `config.toml`) in the footer, but I didn't see options to customize the former message.

I tried to replace this message in all `.html` files but each time I do `blogdown::stop_server()` and `blogdown::serve_site()`, it appears again in these files.

How can I modify this message?

PS: I have the impression that the default academic theme has changed recently and therefore I ask here before StackOverflow, but tell me if this is the wrong place for this sort of question.

**Comment by gcushen** [comment] 2020-09-11 16:25
Closing as this is not a bug. See https://wowchemy.com/plans/ for easily removing the message.

**Closed by gcushen** 2020-09-11 16:25 UTC
