### ISSUE TITLE
hugo cannot find config.yml 

### ISSUE THREAD

**Issue by sidhomj** [wowchemy/starter-academic#130] opened 2020-10-09 06:37 UTC
My understanding is when using the following command:

```
hugo new --kind talk

```

it looks into the static/admin/config.yml file to provide the template. However, when I call this command, I only get the following:

```
---
title: "Check"
date: 2020-10-09T02:36:51-04:00
draft: true
---
```
I may be missing something simple, so any help would be appreciated!

**Comment by gcushen** [comment] 2020-10-10 10:05
The command you are attempting to use doesn't specify a file name. Closing this as it's not a bug - `hugo new --kind talk talk/test` works fine (tested with the latest version of the Academic Starter template).

Note that `static/admin/config.yml` is for Netlify CMS, not Hugo archetypes.

This is a Hugo command, so if there are this issues with it, consider trying the latest  Academic Starter template or reporting the issue on the Hugo forums/Github.

**Closed by gcushen** 2020-10-10 10:05 UTC
