### ISSUE TITLE
How to animate my website

### ISSUE THREAD

**Issue by r4work** [wowchemy/starter-academic#140] opened 2020-11-03 06:11 UTC
Hi! 

I have been using wowchemy academic theme and built my website with some initial help tips from @gcushen and @rodrigoalcarazdelaosa. I want to animate menu icons (e.g. 'recent and upcoming') on my home page. Using the [support document](https://wowchemy.com/docs/customization/#override-a-template), I feel such changes in home page requires editing themes/academic/layouts/partials/ to layouts/partials. Unfortunately, I am unable to locate the 'themes/academic' folder in [my repository](https://github.com/r4work/starter-academic).

Need expert advice on this.

**Comment by rodrigoalcarazdelaosa** [comment] 2020-11-03 07:16
If you need source files you have to get them from [this repo](https://github.com/wowchemy/wowchemy-hugo-modules)

**Comment by r4work** [comment] 2020-11-03 09:15
Thank you @rodrigoalcarazdelaosa! Sorry, I am a beginner. I will appreciate specific location folders/files in the suggested [repo](https://github.com/wowchemy/wowchemy-hugo-modules) that needs to be copied/edited into the specific location of [my repo](https://github.com/r4work/starter-academic). Further, I need to know how to animate. An example will be helpful.
Thanks in advance.

**Comment by gcushen** [comment] 2020-11-05 23:53
Closing this as it's not a bug. For animation ideas check out similar discussions on https://discourse.gohugo.io/ etc. and add them to your custom CSS https://wowchemy.com/docs/customization/#customize-style-css

**Closed by gcushen** 2020-11-05 23:53 UTC
